### ISSUE TITLE
Crash on language settings

### ISSUE THREAD

**Issue by flammie** [divvun/giellakbd-android#39]
I tried to test #35 but only get crashes when trying to open language selection setting with this stack trace
```
java.lang.RuntimeException: Failed to call observer method
	at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:226)
	at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194)
	at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:186)
	at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:37)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
	at com.android.settingslib.core.lifecycle.ObservablePreferenceFragment.onStart(ObservablePreferenceFragment.java:98)
	at com.android.settings.core.InstrumentedPreferenceFragment.onStart(InstrumentedPreferenceFragment.java:73)
	at com.android.settings.SettingsPreferenceFragment.onStart(SettingsPreferenceFragment.java:1112)
	at com.android.settings.dashboard.DashboardFragment.onStart(DashboardFragment.java:219)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:3019)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:568)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:277)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1331)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2772)
	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2722)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:273)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:486)
	at com.android.settingslib.core.lifecycle.ObservableActivity.onStart(ObservableActivity.java:74)
	at com.android.settings.SettingsActivity.onStart(SettingsActivity.java:589)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1566)
	at android.app.Activity.performStart(Activity.java:8572)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3934)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8410)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.ClassCastException: com.android.settingslib.inputmethod.InputMethodSubtypePreference cannot be cast to com.android.settingslib.PrimarySwitchPreference
	at com.android.settingslib.inputmethod.InputMethodAndSubtypeUtilCompat.saveInputMethodSubtypeListForUserInternal(InputMethodAndSubtypeUtilCompat.java:249)
	at com.android.settingslib.inputmethod.InputMethodAndSubtypeUtilCompat.saveInputMethodSubtypeList(InputMethodAndSubtypeUtilCompat.java:174)
	at com.android.settingslib.inputmethod.InputMethodAndSubtypeEnablerManagerCompat.setAutoSelectionSubtypesEnabled(InputMethodAndSubtypeEnablerManagerCompat.java:227)
	at com.android.settingslib.inputmethod.InputMethodAndSubtypeEnablerManagerCompat.updateAutoSelectionPreferences(InputMethodAndSubtypeEnablerManagerCompat.java:276)
	at com.android.settingslib.inputmethod.InputMethodAndSubtypeEnablerManagerCompat.refresh(InputMethodAndSubtypeEnablerManagerCompat.java:88)
	at com.android.settings.inputmethod.InputMethodAndSubtypePreferenceController.onStart(InputMethodAndSubtypePreferenceController.java:60)
	at com.android.settingslib.core.lifecycle.Lifecycle.onStart(Lifecycle.java:124)
	at com.android.settingslib.core.lifecycle.Lifecycle.-$$Nest$monStart(Unknown Source:0)
	at com.android.settingslib.core.lifecycle.Lifecycle$LifecycleProxy.onLifecycleEvent(Lifecycle.java:222)
	at java.lang.reflect.Method.invoke(Native Method)
	at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:222)
	... 38 more
```

**Comment by snomos** [comment]
This is still the case with the latest version of the Divvun Dev Keyboards app. It looks like the following:

![image](https://github.com/user-attachments/assets/9cb781b1-9a5a-42b9-a3d9-28e046a74a21)

![image](https://github.com/user-attachments/assets/b3f8a2e2-b7f5-472a-8b58-ed341aeee9ec)

@flammie what is the Android version? What is the Divvun Dev Keyboard app version?

**Comment by flammie** [comment]
this is an old xiaomi redmi 10c with miui 14.0.6 and android 13 
![Screenshot_2024-08-20-11-41-12-346_com android settings](https://github.com/user-attachments/assets/377c7635-f01e-4662-8fed-0b63478fbf9a)
